### ISSUE TITLE
Custom CSS for share icons loads inconsistently

### ISSUE THREAD

**Issue by miket2marcom** [ComeetCo/comeet-wp-plugin#8]
We are trying to use the external CSS feature to style the Comeet social share icons differently, but these new styles are only loaded sometimes, probably less than half the time. When the new styles don't load, it just displays the default square Comeet social share icons.

We made sure to add the domain that the CSS is on to the domains list in our Comeet account, per the documentation.

By the way, not sure if this is related, but as I've been testing this feature, once I have this "Set CSS Cache to false" option checked, I am unable to uncheck it and save. If I uncheck that option, and save the settings, it just reverts to it being checked.

<img width="545" alt="Screen Shot 2021-09-24 at 3 05 20 PM" src="https://user-images.githubusercontent.com/45983835/134727775-43291b25-4359-4d01-b3f5-cfa38ffee9e4.png">

Thanks for your help.

**Comment by YonatanRan** [comment]
Thanks for letting me know about the css-cache issue. 
It has been fixed in the latest version (2.18.6)
As for the main issue described, the CSS not loading on a consistent basis, I can't recreate this.
On all my tests, as long as the css passes the Comeet sanitation, it is properly applied to the iFrame content.

Are changes being made to the CSS that might be causing it to no load/applied to the iFrame content?

When it does not load, please look at your network tab, search for "sanitize", if it didn't load for what ever reason, it should be red, and let me know what the response status code is + what the actual response is.

Thanks.

**Comment by miket2marcom** [comment]
Hi Yonatan,

Thanks for the reply. We've updated to 2.18.6 on our test site but still having an issue getting the custom social icon styles working. I will show you this later during our meeting today.

Thanks
